### ISSUE TITLE
Update feedstock to 3.0.0

### ISSUE THREAD

**Issue by felixgwilliams** [conda-forge/awswrangler-feedstock#104]
### Comment:

I was excited about this release as I understand it is compatible with python 3.11, so I was wondering about the progress with bringing it to conda forge.

I notice that the autotick bot has errored with the following message:

```
No error information available for version '3.0.0'.
```

I really appreciate all your work with building this super-useful package and making it available in conda.

**Comment by kukushking** [comment]
Hi @felixgwilliams thank you for the kind words, we are very happy you are enjoying the library! Conda release 3 is in progress - I've just opened a PR: https://github.com/conda-forge/awswrangler-feedstock/pull/105

**Comment by felixgwilliams** [comment]
Thank you @kukushking. Looks like it's all in hand! I'll close this issue now
