### ISSUE TITLE
2.13.0 release

### ISSUE THREAD

**Issue by gabrielmagno** [conda-forge/awswrangler-feedstock#92]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

AWS Data Wrangler 2.13.0 was released 4 days ago: https://github.com/awslabs/aws-data-wrangler/releases/tag/2.13.0
Will it be launched to conda-forge? I also noticed that 2.12.1 was also not launched.

**Comment by jaidisido** [comment]
Please see this [issue](https://github.com/opensearch-project/opensearch-build/issues/785) and #89
